version: "3.9"

networks:
  my-custom-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

services:
  fn:
    image: junwoogyun/react-docker-app:latest # Docker Hub 이미지
    container_name: react-container
    networks:
      my-custom-network:
        ipv4_address: 192.168.100.10
    ports:
      - "3000:80" # React Nginx 포트 매핑

  yolo:
    image: junwoogyun/flask-opencv-app:latest # Docker Hub 이미지
    container_name: flask-opencv-container
    networks:
      my-custom-network:
        ipv4_address: 192.168.100.100
    ports:
      - "5000:5000" # YOLO Flask 포트 매핑

  predict:
    image: junwoogyun/flask-opencv-app2:latest # Docker Hub 이미지
    container_name: flask-opencv-container2
    networks:
      my-custom-network:
        ipv4_address: 192.168.100.200
    ports:
      - "5002:5002"
      - "5003:5003"
      - "5004:5004" # Predict Flask 포트 매핑
